---


- name: uncompress artifact
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start