---


- name: uncompress artifact
  become: true
  become_method: sudo
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: Executing node
  become: true
  become_method: sudo
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    