---



- name: "download node-exporter."
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /home/ubuntu/
    remote_src: yes

- name: "copy to /usr/local/bin."
  become: true
  copy:
    src: /home/ubuntu/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0777'

- name: "copy service file"
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes

